NovoApp/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Novo.Models.Entity;
using NovoClients.DataAccess.Data;

namespace NovoApp.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DepartmentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Departments
        public async Task<IActionResult> Display()
        {
            var departments = await _context.Departments.ToListAsync();
            return new JsonResult(departments);
        }


        public IActionResult Index()
        {
            return View();
        }

        // GET: Departments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var departments = await _context.Departments
                .FirstOrDefaultAsync(m => m.Id == id);
            if (departments == null)
            {
                return NotFound();
            }

            return View(departments);
        }

        // GET: Departments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,DeptHead,Id,AddedBy,UpdatedBy,CreateDate,UpdateDate,IsDelete")] Departments departments)
        {
            if (ModelState.IsValid)
            {
                _context.Add(departments);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(departments);
        }

        // GET: Departments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var departments = await _context.Departments.FindAsync(id);
            if (departments == null)
            {
                return NotFound();
            }
            return View(departments);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Id,DeptHead,AddedBy,UpdatedBy,CreateDate,UpdateDate,IsDelete")] Departments departments)
        {
            if (id != departments.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(departments);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartmentsExists(departments.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(departments);
        }

        // GET: Departments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var departments = await _context.Departments
                .FirstOrDefaultAsync(m => m.Id == id);
            if (departments == null)
            {
                return NotFound();
            }

            return View(departments);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var departments = await _context.Departments.FindAsync(id);
            _context.Departments.Remove(departments);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task Remove(int id)
        {
            //if (id == null)
            //{
            //    return NotFound();
            //}

            var departments = await _context.Departments.FindAsync(id);
            _context.Departments.Remove(departments);
            await _context.SaveChangesAsync();
            //return true;
            //return RedirectToAction(nameof(Index));
        }

        private bool DepartmentsExists(int id)
        {
            return _context.Departments.Any(e => e.Id == id);
        }
    }
}

NovoApp/Views/Departments/Create.cshtml
@model Novo.Models.Entity.Departments

@{
    ViewData["Title"] = "Create";
    Layout = null;
}

    @*<div class="row">
        <div class="col-md-10" style="margin:auto;">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name" class="control-label"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                    </div>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DeptHead" class="control-label"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DeptHead" class="form-control" />
                    </div>
                    <span asp-validation-for="DeptHead" class="text-danger"></span>
                </div>
                <div class="form-group" hidden>
                    <label asp-for="AddedBy" class="control-label"></label>
                    <input asp-for="AddedBy" type="date" value="@DateTime.Now" class="form-control" />
                    <span asp-validation-for="AddedBy" class="text-danger"></span>
                </div>
                <div class="form-group" hidden>
                    <label asp-for="UpdatedBy" class="control-label"></label>
                    <input asp-for="UpdatedBy" type="date" value="@DateTime.Now" class="form-control" />
                    <span asp-validation-for="UpdatedBy" class="text-danger"></span>
                </div>
                <div class="form-group" hidden>
                    <label asp-for="CreateDate" class="control-label"></label>
                    <input asp-for="CreateDate" type="date" value="@DateTime.Now" class="form-control" />
                    <span asp-validation-for="CreateDate" class="text-danger"></span>
                </div>
                <div class="form-group" hidden>
                    <label asp-for="UpdateDate" class="control-label"></label>
                    <input asp-for="UpdateDate" type="date" value="@DateTime.Now" class="form-control" />
                    <span asp-validation-for="UpdateDate" class="text-danger"></span>
                </div>
                <div class="form-group" hidden>
                    <div class="checkbox">
                        <label>
                            <input asp-for="IsDelete" value="true" /> @Html.DisplayNameFor(model => model.IsDelete)
                        </label>
                    </div>
                </div>
                <div class="form-group row">
                    <input type="submit" value="Create" class="btn btn-primary col-md-12" />
                </div>
            </form>
        </div>
    </div>*@


<div class="row">
    <div class="col-md-10" style="margin:auto;">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name" class="control-label"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control" />
                </div>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="DeptHead" class="control-label"></label>
                </div>
                <div class="col-8">
                    <input asp-for="DeptHead" class="form-control" />
                </div>
                <span asp-validation-for="DeptHead" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="AddedBy" class="control-label"></label>
                <input asp-for="AddedBy" value="@DateTime.Now" class="form-control" />
                <span asp-validation-for="AddedBy" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="UpdatedBy" class="control-label"></label>
                <input asp-for="UpdatedBy" value="@DateTime.Now" class="form-control" />
                <span asp-validation-for="UpdatedBy" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="CreateDate" class="control-label"></label>
                <input asp-for="CreateDate" value="@DateTime.Now" class="form-control" />
                <span asp-validation-for="CreateDate" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="UpdateDate" class="control-label"></label>
                <input asp-for="UpdateDate" value="@DateTime.Now" class="form-control" />
                <span asp-validation-for="UpdateDate" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <div class="checkbox">
                    <label>
                        <input asp-for="IsDelete" value="false" /> @Html.DisplayNameFor(model => model.IsDelete)
                    </label>
                </div>
            </div>
            <div class="form-group row">
                <input type="submit" value="Submit" class="btn btn-primary col-md-12" />
            </div>
        </form>
    </div>
</div>

@*<div>
    <a asp-action="Index">Back to List</a>
</div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NovoApp/Views/Departments/Delete.cshtml
@model Novo.Models.Entity.Departments

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Departments</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AddedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AddedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDelete)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDelete)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

NovoApp/Views/Departments/Details.cshtml
@model Novo.Models.Entity.Departments

@{
    ViewData["Title"] = "Details";
    Layout = null;
}


<div class="col-8" style="margin:auto;">
    <div class="form-group row">
        <div class="col-4">
            <label asp-for="Name"></label>
        </div>
        <div class="col-8">
            <input asp-for="Name" readonly class="form-control" />
        </div>
    </div>

    <div class="form-group row">
        <div class="col-4">
            <label asp-for="DeptHead"></label>
        </div>
        <div class="col-8">
            <input asp-for="DeptHead" readonly class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <a asp-action="Index" class="btn btn-success">Back</a>
    </div>
</div>



@*<h2>Details</h2>

<div>
    <h4>Departments</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AddedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AddedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDelete)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDelete)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>*@

NovoApp/Views/Departments/Edit.cshtml
@model Novo.Models.Entity.Departments

@{
    ViewData["Title"] = "Edit";
    Layout = null;
}

@*<h2>Edit</h2>

<h4>Departments</h4>
<hr />*@
<div class="row">
    <div class="col-md-10" style="margin:auto;">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name" class="control-label"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control" />
                </div>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="DeptHead" class="control-label"></label>
                </div>
                <div class="col-8">
                    <input asp-for="DeptHead" class="form-control" />
                </div>
                <span asp-validation-for="DeptHead" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group" hidden>
                <label asp-for="AddedBy" class="control-label"></label>
                <input asp-for="AddedBy" class="form-control" />
                <span asp-validation-for="AddedBy" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="UpdatedBy" class="control-label"></label>
                <input asp-for="UpdatedBy" class="form-control" />
                <span asp-validation-for="UpdatedBy" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="CreateDate" class="control-label"></label>
                <input asp-for="CreateDate" class="form-control" />
                <span asp-validation-for="CreateDate" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="UpdateDate" class="control-label"></label>
                <input asp-for="UpdateDate" class="form-control" />
                <span asp-validation-for="UpdateDate" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <div class="checkbox">
                    <label>
                        <input asp-for="IsDelete" /> @Html.DisplayNameFor(model => model.IsDelete)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary col-12" />
            </div>
        </form>
    </div>
</div>

@*<div>
    <a asp-action="Index">Back to List</a>
</div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NovoApp/Views/Departments/Index.cshtml
@model IEnumerable<Novo.Models.Entity.Departments>

@{
    ViewData["Title"] = "Index";
}


<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Departments List</li>
                    </ol>
                </nav>
                <div class="row">
                    <div class="col-md-12 table-responsive-md">
                        <a class="btn btn-md btn-outline-success float-md-right" onclick="showInPopupDept('@Url.Action("Create","Departments",null,Context.Request.Scheme)','New Department')">
                            Add new Department
                        </a>
                        <br />
                        <br />

                        <div class="card shadow mb-4">

                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-bordered" id="leaves" width="100%" cellspacing="0">
                                        <thead>
                                            <tr>
                                                <th></th>
                                                <th>Name</th>
                                                <th>Department Head</th>
                                                <th class="text-warning">Actions</th>
                                            </tr>
                                        </thead>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>


    <div class="modal" tabindex="-1" id="form-modal1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                </div>
            </div>
        </div>
    </div>


    
    @section scripts{
        <script src="~/new/lib/datatables.bundle.js"></script>
        <script src="~/new/lib/jsrender/jsrender.min.js"></script>

        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/1.0.7/jsrender.min.js" integrity="sha512-Y6fnBD9Z/4xDuDemzJBaYAQBGD/EOuaonQDW4W3Khf9j6gbvFd+K48MCW9UeMZrs5F/hELIuy7Mjpf/Ss4tRxQ==" crossorigin="anonymous"></script>
        <script src="~/js/site.js"></script>
       
        <script type="text/javascript">
                $(document).ready(function () {

                    $('#leaves').DataTable({
                        ajax: {
                            url: '/departments/display',
                            dataSrc: ''
                        },
                        columns: [
                            {
                                bSortable: 0,
                                width: "30px",
                                className: "dt-right",
                                orderable: !1,
                                render: function (e, a, t, n) {
                                    return '\n <label class="m-checkbox m-checkbox--single m-checkbox--solid m-checkbox--brand">\n <input type="checkbox" value="" class="m-checkable">\n <span></span>\n </label>'
                                }
                            },
                            {
                                bSortable: false,
                                data: 'name'
                            },
                            {
                                bSortable: false,
                                data: 'deptHead'
                            },
                            {
                                bSortable: false,
                                render: function (a, t, n) {
                                    return `\n <span class="dropdown">\n
                                                                                            <a href="javascript:void(0);" class="btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" data-toggle="dropdown" aria-expanded="true">\n<i class="fas fa-ellipsis-h"></i>\n </a>\n
                                                                                                        <div class="dropdown-menu dropdown-menu-right">
                                                                                                        \n <a class="dropdown-item open-details-modal" href="javascript:void(0);" onclick="showInPopupDetail(`+ n.id + `, '@Url.Action("Details","Departments",null,Context.Request.Scheme)','Unit Detail')"><i class="la la-leaf"></i> View Details</a>
                                                                                                        \n <a class="dropdown-item" href="javascript:void(0);" onclick="showInPopupEdit(`+ n.id + `, '@Url.Action("Edit","Departments",null,Context.Request.Scheme)','Unit Detail')"><i class="la la-edit"></i> Modify</a>
                                                                                                        \n <a class="dropdown-item" href="javascript:void(0);" onclick="showInPopupDelete(`+ n.id + `)"><i class="la la-edit"></i> Delete</a>
                                                                                                        \n </div>
                                                                                                    \n </span>\n`
                                }
                            }
                        ],
                        lengthMenu: [10, 25, 50, 100, 200],
                        pageLength: 10,
                        language: {
                            search: "Search:  ",
                            lengthMenu: "Display _MENU_"
                        },
                        headerCallback: function (e, a, t, n, s) {
                            e.getElementsByTagName("th")[0].innerHTML = '\n<label class="m-checkbox m-checkbox--single m-checkbox--solid m-checkbox--brand">\n <input type="checkbox" value="" class="m-group-checkable">\n <span></span>\n </label>'
                        },
                        order: []

                    });

                });

            showInPopupDept = (url, title) => {
                console.log("Hey")
                $.ajax({
                    type: "GET",
                    url: url,
                    success: function (res) {
                        console.log("Oga")
                        console.log(res)
                        $("#form-modal .modal-body").html(res);
                        $("#form-modal .modal-title").html(title);
                        $("#form-modal").modal('show');
                    },
                    error: function (err) {
                        console.log(err)
                    }
                })
            }

                showInPopupDetail = (url, url1, title) => {
                    console.log('Hey')
                    console.log(url1 + '/' + url)
                    var ooo = url1 + '/' + url
                    $.ajax({
                        type: "GET",
                        url: ooo,
                        success: function (res) {
                            console.log("Oga")
                            console.log(res)
                            $("#form-modal1 .modal-body").html(res);
                            $("#form-modal1 .modal-title").html(title);
                            $("#form-modal1").modal('show');
                        },
                        error: function (err) {
                            console.log("Ogaju")
                            console.log(err)
                        }
                    })
                    console.log(data)
        }

        showInPopupEdit = (url, url1, title) => {
            console.log('Hey')
            console.log(url1 + '/' + url)
            var ooo = url1 + '/' + url
            $.ajax({
                type: "GET",
                url: ooo,
                success: function (res) {
                    console.log("Oga")
                    console.log(res)
                    $("#form-modal1 .modal-body").html(res);
                    $("#form-modal1 .modal-title").html(title);
                    $("#form-modal1").modal('show');
                },
                error: function (err) {
                    console.log("Ogaju")
                    console.log(err)
                }
            })
            console.log(data)
        }

        showInPopupDelete = (url) => {
            console.log('Hey')
            //console.log(url1 + '/' + url)
            var ooo = 'departments/Remove/' + url
            $.ajax({
                type: "GET",
                url: ooo,
                success: function (response) {
                    window.location.reload();
                },

                error: function (response) {
                    console.log(response)
                }
                //success: function (res) {
                //    console.log("Oga")
                //    console.log(res)
                //    //$("#form-modal1 .modal-body").html(res);
                //    //$("#form-modal1 .modal-title").html(title);
                //    //$("#form-modal1").modal('show');
                //},
                //error: function (err) {
                //    console.log("Ogaju")
                //    console.log(err)
                //}
            })

        }


        </script>
    }




    @*<h2>Index</h2>

        <p>
            <a asp-action="Create">Create New</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.AddedBy)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.UpdatedBy)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CreateDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.UpdateDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IsDelete)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
        @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AddedBy)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UpdatedBy)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreateDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UpdateDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsDelete)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
        }
            </tbody>
        </table>*@